# Generated by Django 3.2 on 2023-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upwork',
            fields=[
                ('up_id', models.AutoField(primary_key=True, serialize=False)),
                ('up_name', models.CharField(max_length=50)),
                ('up_url', models.CharField(max_length=100)),
            ],
        ),
    ]
