# Generated by Django 3.2 on 2023-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='my_table',
            fields=[
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.TextField()),
                ('JobDescription', models.TextField()),
            ],
        ),
    ]
