# Generated by Django 3.2 on 2023-06-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0002_data_my_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='dataa',
        ),
    ]
