# Generated by Django 3.2 on 2023-06-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0003_rename_data_dataa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataa',
            name='data_id',
        ),
        migrations.RemoveField(
            model_name='my_table',
            name='Job_id',
        ),
        migrations.RemoveField(
            model_name='upwork',
            name='up_id',
        ),
        migrations.AddField(
            model_name='dataa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upwork',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataa',
            name='data_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='my_table',
            name='JobDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='my_table',
            name='JobName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upwork',
            name='up_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='upwork',
            name='up_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
