# Generated by Django 3.2 on 2023-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0004_auto_20230607_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='upwork',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
