# Generated by Django 3.2 on 2023-08-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0006_auto_20230802_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataa',
            name='my_table_entry',
        ),
        migrations.RemoveField(
            model_name='my_table',
            name='upwork_entry',
        ),
    ]
