# Generated by Django 3.2 on 2023-08-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0008_auto_20230802_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataa',
            name='my_table_entry',
        ),
    ]
