# Generated by Django 3.2 on 2023-08-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0010_remove_my_table_upwork_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_table',
            name='upwork_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upwork_app.upwork'),
            preserve_default=False,
        ),
    ]
