# Generated by Django 3.2 on 2023-08-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_app', '0011_my_table_upwork_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataa',
            name='my_table_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upwork_app.my_table'),
            preserve_default=False,
        ),
    ]
